/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : [r]FoX
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_MainMenu                            0
#define GD_Commands                            1
#define GD_AddMenu                             2
#define GD_AddCom                              3
#define GD_DelMenu                             4
#define GD_DelCom                              5

#define GDX_MainMenu                           0
#define GDX_Commands                           1
#define GDX_AddMenu                            2
#define GDX_AddCom                             3
#define GDX_DelMenu                            4
#define GDX_DelCom                             5

#define Project5_CNT 6

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *Project5Wnd;
extern struct Gadget        *Project5GList;
extern struct IntuiMessage   Project5Msg;
extern struct Gadget        *Project5Gadgets[6];
extern UWORD                 Project5Left;
extern UWORD                 Project5Top;
extern UWORD                 Project5Width;
extern UWORD                 Project5Height;
extern UBYTE                *Project5Wdt;
extern struct MinList        MainMenu0List;
extern struct MinList        Commands0List;
extern struct TextAttr       topaz8;
extern UWORD                 Project5GTypes[];
extern struct NewGadget      Project5NGad[];
extern ULONG                 Project5GTags[];

extern int MainMenuClicked( void );
extern int CommandsClicked( void );
extern int AddMenuClicked( void );
extern int AddComClicked( void );
extern int DelMenuClicked( void );
extern int DelComClicked( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleProject5IDCMP( void );
