/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_MSGLIST                             0
#define GD_FOLDER                              1
#define GD_MESSAGES                            2
#define GD_BYTES                               3
#define GD_READ                                4
#define GD_WRITE                               5
#define GD_DELETE                              6
#define GD_GETMAIL                             7
#define GD_STAT                                8

#define GDX_MSGLIST                            0
#define GDX_FOLDER                             1
#define GDX_MESSAGES                           2
#define GDX_BYTES                              3
#define GDX_READ                               4
#define GDX_WRITE                              5
#define GDX_DELETE                             6
#define GDX_GETMAIL                            7
#define GDX_STAT                               8

#define Project0_CNT 9

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *Project0Wnd;
extern struct Gadget        *Project0GList;
extern struct Gadget        *Project0Gadgets[9];
extern UWORD                 Project0Left;
extern UWORD                 Project0Top;
extern UWORD                 Project0Width;
extern UWORD                 Project0Height;
extern UBYTE                *Project0Wdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern UBYTE                *FOLDER0Labels[];
extern UWORD                 Project0GTypes[];
extern struct NewGadget      Project0NGad[];
extern ULONG                 Project0GTags[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void Project0Render( void );
extern int OpenProject0Window( void );
extern void CloseProject0Window( void );
