/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : [r]FoX
 */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <clib/exec_protos.h>
#include <clib/intuition_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/utility_protos.h>
#include <string.h>

#include <pragmas/exec_pragmas.h>
#include <pragmas/intuition_pragmas.h>
#include <pragmas/gadtools_pragmas.h>
#include <pragmas/graphics_pragmas.h>
#include <pragmas/utility_pragmas.h>

#include "config.h"

struct Screen         *Scr = NULL;
UBYTE                 *PubScreenName = NULL;
APTR                   VisualInfo = NULL;
struct Window         *ConfigWindowWnd = NULL;
struct Gadget         *ConfigWindowGList = NULL;
struct IntuiMessage    ConfigWindowMsg;
struct Gadget         *ConfigWindowGadgets[7];
UWORD                  ConfigWindowLeft = 10;
UWORD                  ConfigWindowTop = 15;
UWORD                  ConfigWindowWidth = 283;
UWORD                  ConfigWindowHeight = 131;
UBYTE                 *ConfigWindowWdt = (UBYTE *)"DCIRC Configuration";

struct TextAttr topaz8 = {
	( STRPTR )"topaz.font", 8, 0x00, 0x01 };

struct IntuiText ConfigWindowIText[] = {
	3, 5, JAM1,12, 7, &topaz8, (UBYTE *)"DCIRC Vø.2 User-Setup            ", &ConfigWindowIText[1],
	2, 0, JAM1,11, 16, &topaz8, (UBYTE *)"-----------------------------", NULL };

UWORD ConfigWindowGTypes[] = {
	BUTTON_KIND,
	BUTTON_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND
};

struct NewGadget ConfigWindowNGad[] = {
	11, 110, 81, 13, (UBYTE *)"Save", NULL, GD_SAVE_GAD, PLACETEXT_IN, NULL, (APTR)SAVE_GADClicked,
	94, 110, 81, 13, (UBYTE *)"Cancel", NULL, GD_CANCEL_GAD, PLACETEXT_IN, NULL, (APTR)CANCEL_GADClicked,
	10, 27, 159, 13, (UBYTE *)"Nickname", NULL, GD_NICK_GAD, PLACETEXT_RIGHT, NULL, (APTR)NICK_GADClicked,
	10, 84, 159, 14, (UBYTE *)"Realname", NULL, GD_REAL_GAD, PLACETEXT_RIGHT, NULL, (APTR)REAL_GADClicked,
	10, 41, 159, 14, (UBYTE *)"ServerName", NULL, GD_SERVER_GAD, PLACETEXT_RIGHT, NULL, (APTR)SERVER_GADClicked,
	10, 70, 159, 13, (UBYTE *)"Channel", NULL, GD_CHANNEL_GAD, PLACETEXT_RIGHT, NULL, (APTR)CHANNEL_GADClicked,
	10, 56, 159, 13, (UBYTE *)"Port", NULL, GD_PORT_GAD, PLACETEXT_RIGHT, NULL, (APTR)PORT_GADClicked
};

ULONG ConfigWindowGTags[] = {
	(GT_Underscore), '_', (TAG_DONE),
	(GT_Underscore), '_', (TAG_DONE),
	(GTST_String), (ULONG)"DCIRC", (GTST_MaxChars), 256, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE),
	(GTST_String), (ULONG)"DigitalCorruption", (GTST_MaxChars), 256, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE),
	(GTST_String), (ULONG)"us.elitenet.org", (GTST_MaxChars), 256, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE),
	(GTST_String), (ULONG)"#EliteCafe", (GTST_MaxChars), 256, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE),
	(GTIN_Number), 6667, (GTIN_MaxChars), 10, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE)
};

int SetupScreen( void )
{
	if ( ! ( Scr = LockPubScreen( PubScreenName )))
		return( 1L );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		UnlockPubScreen( NULL, Scr );
		Scr = NULL;
	}
}

void ConfigWindowRender( void )
{
	UWORD		offx, offy;

	offx = ConfigWindowWnd->BorderLeft;
	offy = ConfigWindowWnd->BorderTop;

	PrintIText( ConfigWindowWnd->RPort, ConfigWindowIText, offx, offy );
}

int HandleConfigWindowIDCMP( void )
{
	struct IntuiMessage	*m;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( ConfigWindowWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&ConfigWindowMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( ConfigWindowMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( ConfigWindowWnd );
				ConfigWindowRender();
				GT_EndRefresh( ConfigWindowWnd, TRUE );
				break;

			case	IDCMP_CLOSEWINDOW:
				running = ConfigWindowCloseWindow();
				break;

			case	IDCMP_ACTIVEWINDOW:
				running = ConfigWindowActiveWindow();
				break;

			case	IDCMP_VANILLAKEY:
				running = ConfigWindowVanillaKey();
				break;

			case	IDCMP_GADGETUP:
			case	IDCMP_GADGETDOWN:
				func = ( void * )(( struct Gadget * )ConfigWindowMsg.IAddress )->UserData;
				running = func();
				break;
		}
	}
	return( running );
}

int OpenConfigWindowWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		offx = Scr->WBorLeft, offy = Scr->WBorTop + Scr->RastPort.TxHeight + 1;

	if ( ! ( g = CreateContext( &ConfigWindowGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < ConfigWindow_CNT; lc++ ) {

		CopyMem((char * )&ConfigWindowNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = &topaz8;
		ng.ng_LeftEdge  += offx;
		ng.ng_TopEdge   += offy;

		ConfigWindowGadgets[ lc ] = g = CreateGadgetA((ULONG)ConfigWindowGTypes[ lc ], g, &ng, ( struct TagItem * )&ConfigWindowGTags[ tc ] );

		while( ConfigWindowGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( ConfigWindowWnd = OpenWindowTags( NULL,
				WA_Left,	ConfigWindowLeft,
				WA_Top,		ConfigWindowTop,
				WA_Width,	ConfigWindowWidth,
				WA_Height,	ConfigWindowHeight + offy,
				WA_IDCMP,	BUTTONIDCMP|STRINGIDCMP|INTEGERIDCMP|IDCMP_GADGETDOWN|IDCMP_CLOSEWINDOW|IDCMP_ACTIVEWINDOW|IDCMP_VANILLAKEY|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_SIZEGADGET|WFLG_DRAGBAR|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH,
				WA_Gadgets,	ConfigWindowGList,
				WA_Title,	ConfigWindowWdt,
				WA_ScreenTitle,	"GadToolsBox V2.0b © 1991-1993",
				WA_PubScreen,	Scr,
				WA_MinWidth,	67,
				WA_MinHeight,	21,
				WA_MaxWidth,	668,
				WA_MaxHeight,	277,
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( ConfigWindowWnd, NULL );

	ConfigWindowRender();

	return( 0L );
}

void CloseConfigWindowWindow( void )
{
	if ( ConfigWindowWnd        ) {
		CloseWindow( ConfigWindowWnd );
		ConfigWindowWnd = NULL;
	}

	if ( ConfigWindowGList      ) {
		FreeGadgets( ConfigWindowGList );
		ConfigWindowGList = NULL;
	}
}

