/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : [r]FoX
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_SAVE_GAD                            0
#define GD_CANCEL_GAD                          1
#define GD_NICK_GAD                            2
#define GD_REAL_GAD                            3
#define GD_SERVER_GAD                          4
#define GD_CHANNEL_GAD                         5
#define GD_PORT_GAD                            6

#define GDX_SAVE_GAD                           0
#define GDX_CANCEL_GAD                         1
#define GDX_NICK_GAD                           2
#define GDX_REAL_GAD                           3
#define GDX_SERVER_GAD                         4
#define GDX_CHANNEL_GAD                        5
#define GDX_PORT_GAD                           6

#define ConfigWindow_CNT 7

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *ConfigWindowWnd;
extern struct Gadget        *ConfigWindowGList;
extern struct IntuiMessage   ConfigWindowMsg;
extern struct Gadget        *ConfigWindowGadgets[7];
extern UWORD                 ConfigWindowLeft;
extern UWORD                 ConfigWindowTop;
extern UWORD                 ConfigWindowWidth;
extern UWORD                 ConfigWindowHeight;
extern UBYTE                *ConfigWindowWdt;
extern struct TextAttr       topaz8;
extern struct IntuiText      ConfigWindowIText[];
extern UWORD                 ConfigWindowGTypes[];
extern struct NewGadget      ConfigWindowNGad[];
extern ULONG                 ConfigWindowGTags[];

extern int SAVE_GADClicked( void );
extern int CANCEL_GADClicked( void );
extern int NICK_GADClicked( void );
extern int REAL_GADClicked( void );
extern int SERVER_GADClicked( void );
extern int CHANNEL_GADClicked( void );
extern int PORT_GADClicked( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void ConfigWindowRender( void );
extern int HandleConfigWindowIDCMP( void );
extern int ConfigWindowCloseWindow();
extern int ConfigWindowActiveWindow();
extern int ConfigWindowVanillaKey();
extern int OpenConfigWindowWindow( void );
extern void CloseConfigWindowWindow( void );
