/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : [r]FoX
 */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <clib/exec_protos.h>
#include <clib/intuition_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/utility_protos.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <proto/intuition.h>
#include <time.h>

#include "NodConWindow.h"

struct Screen         *Scr = NULL;
UBYTE                 *PubScreenName = "Workbench";
APTR                   VisualInfo = NULL;
struct Window         *NodCon_GUIWnd = NULL;
struct Gadget         *NodCon_GUIGList = NULL;
struct IntuiMessage    NodCon_GUIMsg;
struct Gadget         *NodCon_GUIGadgets[15];
UWORD                  NodCon_GUILeft = 10;
UWORD                  NodCon_GUITop = 15;
UWORD                  NodCon_GUIWidth = 252;
UWORD                  NodCon_GUIHeight = 137;
UBYTE                 *NodCon_GUIWdt = (UBYTE *)"NodConGUI V1.1 by [r]FoX";

struct TextAttr topaz8 = {
	( STRPTR )"topaz.font", 8, 0x00, 0x01 };

UWORD NodCon_GUIGTypes[] = {
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND
};

struct NewGadget NodCon_GUINGad[] = {
	0, 0, 26, 11, (UBYTE *)"1", NULL, GD_Node_gad1, PLACETEXT_LEFT, NULL, (APTR)Node_gad1Clicked,
	26, 0, 26, 11, (UBYTE *)"2", NULL, GD_Node_gad2, PLACETEXT_LEFT, NULL, (APTR)Node_gad2Clicked,
	52, 0, 26, 11, (UBYTE *)"3", NULL, GD_Node_gad3, PLACETEXT_LEFT, NULL, (APTR)Node_gad3Clicked,
	80, 0, 26, 11, (UBYTE *)"4", NULL, GD_Node_gad4, PLACETEXT_LEFT, NULL, (APTR)Node_gad4Clicked,
	108, 0, 26, 11, (UBYTE *)"5", NULL, GD_Node_gad5, PLACETEXT_LEFT, NULL, (APTR)Node_gad5Clicked,
	136, 0, 26, 11, (UBYTE *)"6", NULL, GD_Node_gad6, PLACETEXT_LEFT, NULL, (APTR)Node_gad6Clicked,
	164, 0, 26, 11, (UBYTE *)"7", NULL, GD_Node_gad7, PLACETEXT_LEFT, NULL, (APTR)Node_gad7Clicked,
	192, 0, 26, 11, (UBYTE *)"8", NULL, GD_Node_gad8, PLACETEXT_LEFT, NULL, (APTR)Node_gad8Clicked,
	220, 0, 26, 11, (UBYTE *)"9", NULL, GD_Node_gad9, PLACETEXT_LEFT, NULL, (APTR)Node_gad9Clicked,
	38, 35, 152, 14, (UBYTE *)"Close Screen", NULL, GD_SXClose, PLACETEXT_IN, NULL, (APTR)SXCloseClicked,
	38, 17, 152, 14, (UBYTE *)"Open Screen", NULL, GD_SXOpen, PLACETEXT_IN, NULL, (APTR)SXOpenClicked,
	38, 53, 152, 14, (UBYTE *)"Shut Down", NULL, GD_ShutNode, PLACETEXT_IN, NULL, (APTR)ShutNodeClicked,
	38, 71, 152, 14, (UBYTE *)"Launch up", NULL, GD_LaunchNode, PLACETEXT_IN, NULL, (APTR)LaunchNodeClicked,
	38, 89, 152, 14, (UBYTE *)"User Chat", NULL, GD_OpenChat, PLACETEXT_IN, NULL, (APTR)OpenChatClicked,
	38, 107, 152, 14, (UBYTE *)"Kick User", NULL, GD_KickUser, PLACETEXT_IN, NULL, (APTR)KickUserClicked
};

void CloseNodCon_GUIWindow(void);
int OpenNodCon_GUIWindow(void);
int HandleNodCon_GUIIDCMP( void );
void CloseDownScreen( void );
int SetupScreen( void );
void CloseNodCon_GUIWindow(void);


ULONG NodCon_GUIGTags[] = {
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE)
};

int SetupScreen( void )
{
	if ( ! ( Scr = LockPubScreen( PubScreenName )))
		return( 1L );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		UnlockPubScreen( NULL, Scr );
		Scr = NULL;
	}
}

int HandleNodCon_GUIIDCMP( void )
{
	struct IntuiMessage	*m;
	//int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( NodCon_GUIWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&NodCon_GUIMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( NodCon_GUIMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( NodCon_GUIWnd );
				GT_EndRefresh( NodCon_GUIWnd, TRUE );
				break;

			case	IDCMP_CLOSEWINDOW:
			        CloseNodCon_GUIWindow();
				break;

			case	IDCMP_GADGETUP:
				//func = ( void * )(( struct Gadget * )NodCon_GUIMsg.IAddress )->UserData;
				//running = func();
				break;
		}
	}
	return( running );
}

int OpenNodCon_GUIWindow(void)
{
	struct NewGadget ng;
	struct Gadget	 *g;
	UWORD  lc, tc;
	UWORD  offx = Scr->WBorLeft, offy = Scr->WBorTop + Scr->RastPort.TxHeight + 1;

	if(!(g = CreateContext(&NodCon_GUIGList))) return(1L);

	for(lc=0, tc=0; lc < NodCon_GUI_CNT; lc++)
        {
                CopyMem((char *) &NodCon_GUINGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = &topaz8;
		ng.ng_LeftEdge  += offx;
		ng.ng_TopEdge   += offy;

		NodCon_GUIGadgets[ lc ] = g = CreateGadgetA((ULONG)NodCon_GUIGTypes[ lc ], g, &ng, ( struct TagItem * )&NodCon_GUIGTags[ tc ] );

		while( NodCon_GUIGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( NodCon_GUIWnd = OpenWindowTags( NULL,
				WA_Left,	NodCon_GUILeft,
				WA_Top,		NodCon_GUITop,
				WA_Width,	NodCon_GUIWidth,
				WA_Height,	NodCon_GUIHeight + offy,
				WA_IDCMP,	CHECKBOXIDCMP|BUTTONIDCMP|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH,
				WA_Gadgets,	NodCon_GUIGList,
				WA_Title,	NodCon_GUIWdt,
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( NodCon_GUIWnd, NULL );

	return( 0L );
}

void CloseNodCon_GUIWindow(void)
{
	if(NodCon_GUIWnd)
        {
		CloseWindow(NodCon_GUIWnd);
		NodCon_GUIWnd = NULL;
	}

	if(NodCon_GUIGList)
        {
		FreeGadgets( NodCon_GUIGList );
		NodCon_GUIGList = NULL;
	}
}

void main(void)
{
        OpenNodCon_GUIWindow();
        Delay(400);
        CloseNodCon_GUIWindow();
        exit(TRUE);
        
}